services:
  - type: web
    name: blogcraft-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: CLOUDINARY_PRESET
        sync: false

